croft:
  build: ../croft
  env_file: .dev
  links:
    - rabbitmq
  ports:
    - "8080:8080"
    - "1700:1700/udp"

jolie:
  build: ../jolie
  env_file: .dev
  links:
    - rabbitmq
    - influxdb

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"
  volumes:
    - /var/lib/docker/rabbitmq:/data/mnesia

influxdb:
  image: tutum/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090"
    - "8099"
  volumes:
    - /var/lib/docker/influxdb:/data
