mongodb:
  build: ./build/mongodb
  volumes:
    - /var/lib/docker/mongo/mongodb:/data/db
  command: mongod --smallfiles
  ports:
    - "27017:27017"

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"
  volumes:
    - /var/lib/docker/rabbitmq:/data/mnesia
      
influxdb:
  image: johanstokking/influxdb:latest
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090"
    - "8099"
  volumes:
    - /var/lib/docker/influxdb:/data

jolie:
  build: ../jolie
  env_file: ../jolie/.staging
  links:
    - rabbitmq
    - influxdb
    - mongodb

croft:
  build: ../croft
  env_file: ../croft/.staging
  links:
    - rabbitmq
  ports:
    - "8080:8080"
    - "1700:1700/udp"
