mongodb:
  build: ./build/mongodb
  volumes:
    - /data/mongo/mongodb:/data/db
  command: mongod --smallfiles
  ports:
    - "27017:27017"

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"
  volumes:
    - /data/rabbitmq:/data/mnesia

mosquitto:
  image: ansi/mosquitto
  ports:
    - "1883:1883"

jolie:
  build: ../jolie
  env_file: ../jolie/.staging
  links:
    - rabbitmq
    - mongodb
    - mosquitto

croft:
  build: ../croft
  env_file: ../croft/.staging
  links:
    - rabbitmq
  ports:
    - "8080:8080"
    - "1700:1700/udp"

nodered:
  image: cpswan/node-red
  volumes:
    - /data/node-red/:/root/.node-red/
  ports:
    - "1880:1880"
